/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx}',
  ],
  theme: {
    borderRadius: {
      none: '0',
      DEFAULT: '0.125rem',
      sm: '0.125rem',
      md: '0.125rem',
      lg: '0.25rem',
      xl: '0.5rem',
      '2xl': '0.75rem',
      full: '0.75rem',
    },
    extend: {
      fontFamily: {
        heading: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
      },
      colors: {
        'on-secondary-fixed-variant': '#495f69',
        'on-error-container': '#782232',
        'on-tertiary-fixed': '#333d55',
        'inverse-surface': '#0c0f10',
        'surface-bright': '#f8f9fa',
        'on-error': '#fff7f7',
        'surface-dim': '#d1dce0',
        'inverse-primary': '#facc15',
        'on-tertiary': '#f9f8ff',
        'on-surface': '#2b3437',
        'error': '#9e3f4e',
        'surface-container-high': '#e3e9ec',
        'error-container': '#ff8b9a',
        'on-secondary-container': '#40555f',
        'tertiary': '#545f78',
        'on-primary': '#2b3437',
        'background': '#f8f9fa',
        'tertiary-container': '#d5dffd',
        'on-secondary': '#f2faff',
        'tertiary-fixed': '#d5dffd',
        'inverse-on-surface': '#9b9d9e',
        'surface-container-low': '#f1f4f6',
        'secondary': '#4d626c',
        'on-background': '#2b3437',
        'on-surface-variant': '#586064',
        'secondary-container': '#cfe6f2',
        'primary-container': '#fef9c3',
        'surface': '#f8f9fa',
        'surface-variant': '#dbe4e7',
        'on-primary-fixed-variant': '#854d0e',
        'on-primary-container': '#713f12',
        'error-dim': '#4f0116',
        'surface-container': '#eaeff1',
        'on-tertiary-fixed-variant': '#4f5a72',
        'primary-fixed': '#fef9c3',
        'tertiary-dim': '#49536b',
        'secondary-dim': '#415660',
        'secondary-fixed': '#cfe6f2',
        'primary-fixed-dim': '#fde047',
        'primary': '#eab308',
        'secondary-fixed-dim': '#c1d8e4',
        'outline-variant': '#abb3b7',
        'on-tertiary-container': '#455068',
        'on-primary-fixed': '#713f12',
        'on-secondary-fixed': '#2d424c',
        'tertiary-fixed-dim': '#c7d1ee',
        'surface-container-lowest': '#ffffff',
        'primary-dim': '#ca8a04',
        'surface-container-highest': '#dbe4e7',
        'outline': '#737c7f',
        'surface-tint': '#eab308',
      },
    },
  },
  plugins: [],
};
