#!/usr/bin/env bash
# prompts.sh — interactively collect lemon-stack parameters and write parameters.env.
# Re-runnable: existing values become defaults.

set -euo pipefail

cd "$(dirname "$0")"
OUT=parameters.env

# Load existing values as defaults if file exists.
declare -A DEF
if [[ -f $OUT ]]; then
  while IFS='=' read -r k v; do
    [[ -z $k || $k == \#* ]] && continue
    DEF[$k]=$v
  done < <(grep -E '^[A-Z_][A-Z0-9_]*=' "$OUT")
fi

ask() {
  local key=$1 prompt=$2 default=${DEF[$1]:-${3:-}} val
  if [[ -n $default ]]; then
    read -r -p "$prompt [$default]: " val
    val=${val:-$default}
  else
    read -r -p "$prompt: " val
  fi
  printf '%s' "$val"
}

ask_secret() {
  # Generate a 32-byte hex secret unless the user provides one.
  local key=$1 prompt=$2 existing=${DEF[$1]:-} val
  if [[ -n $existing ]]; then
    printf '%s' "$existing"; return
  fi
  read -r -p "$prompt [auto-generate]: " val
  if [[ -z $val ]]; then
    val=$(openssl rand -hex 32)
  fi
  printf '%s' "$val"
}

ask_components() {
  local existing=${DEF[COMPONENTS]:-openbao,monitoring} val
  echo "Optional components (comma-separated, no spaces). Choose from: openbao, monitoring, n8n, pihole" >&2
  read -r -p "  components [$existing]: " val
  printf '%s' "${val:-$existing}"
}

echo "lemon-stack setup — interactive prompts"
echo "Press Enter to accept defaults. Existing parameters.env values pre-fill."
echo

DOMAIN=$(ask DOMAIN "Your domain (e.g. example.com)" "example.com")
GITHUB_ORG=$(ask GITHUB_ORG "GitHub org for auto-deploy")
GITHUB_USERNAME=$(ask GITHUB_USERNAME "Your GitHub username")
ADMIN_EMAIL=$(ask ADMIN_EMAIL "Admin email")
ADMIN_USERNAME=$(ask ADMIN_USERNAME "Linux username on this host" "$(id -un)")
USER_HOME=$(ask USER_HOME "Home directory" "$HOME")
HOSTNAME_VAL=$(ask HOSTNAME "Hostname for this server" "$(hostname)")
TIMEZONE=$(ask TIMEZONE "Timezone" "$(cat /etc/timezone 2>/dev/null || echo UTC)")

echo
echo "--- network ---"
SERVER_IP=$(ask SERVER_IP "LAN IP (homelab) or 0.0.0.0 (VPS)" "0.0.0.0")

echo
echo "--- Cloudflare Tunnel ---"
echo "Create a tunnel at: https://one.dash.cloudflare.com → Networks → Tunnels"
CLOUDFLARE_TUNNEL_TOKEN=$(ask CLOUDFLARE_TUNNEL_TOKEN "Cloudflare Tunnel install token")

echo
echo "--- Authentik bootstrap (leave blank to auto-generate) ---"
AUTHENTIK_SECRET_KEY=$(ask_secret AUTHENTIK_SECRET_KEY "Authentik SECRET_KEY")
AUTHENTIK_BOOTSTRAP_PASSWORD=$(ask_secret AUTHENTIK_BOOTSTRAP_PASSWORD "Authentik admin bootstrap password")
AUTHENTIK_BOOTSTRAP_TOKEN=$(ask_secret AUTHENTIK_BOOTSTRAP_TOKEN "Authentik bootstrap API token")
AUTHENTIK_DB_PASSWORD=$(ask_secret AUTHENTIK_DB_PASSWORD "Authentik DB owner password")

echo
COMPONENTS=$(ask_components)

echo
echo "--- optional secrets (skip with Enter if not using) ---"
TELEGRAM_BOT_TOKEN=$(ask TELEGRAM_BOT_TOKEN "Telegram bot token")
TELEGRAM_CHAT_ID=$(ask TELEGRAM_CHAT_ID "Telegram chat ID")
PIHOLE_WEBPASSWORD=""
if [[ ,$COMPONENTS, == *,pihole,* ]]; then
  PIHOLE_WEBPASSWORD=$(ask_secret PIHOLE_WEBPASSWORD "Pi-hole web UI password")
fi

# Write parameters.env atomically.
tmp=$(mktemp)
cat > "$tmp" <<EOF
# Generated by setup/prompts.sh on $(date -u +%FT%TZ). chmod 600.
DOMAIN=$DOMAIN
GITHUB_ORG=$GITHUB_ORG
GITHUB_USERNAME=$GITHUB_USERNAME
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_USERNAME=$ADMIN_USERNAME
USER_HOME=$USER_HOME
HOSTNAME=$HOSTNAME_VAL
TIMEZONE=$TIMEZONE
SERVER_IP=$SERVER_IP
CLOUDFLARE_TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
AUTHENTIK_SECRET_KEY=$AUTHENTIK_SECRET_KEY
AUTHENTIK_BOOTSTRAP_PASSWORD=$AUTHENTIK_BOOTSTRAP_PASSWORD
AUTHENTIK_BOOTSTRAP_TOKEN=$AUTHENTIK_BOOTSTRAP_TOKEN
AUTHENTIK_DB_PASSWORD=$AUTHENTIK_DB_PASSWORD
COMPONENTS=$COMPONENTS
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
PIHOLE_WEBPASSWORD=$PIHOLE_WEBPASSWORD
EOF
mv "$tmp" "$OUT"
chmod 600 "$OUT"
echo
echo "Wrote $OUT (mode 600). Edit it directly any time, then re-run setup.sh."
